### ISSUE TITLE
HMaster fails to start with latest Java 1.8.0_121

### ISSUE THREAD

**Issue by shvachko** [GiraffaFS/giraffa#233]
HMaster cannot bind to the configured address. I believe this is related to {{-preferIPv4Stack}}. It works fine with java 1.8.0.40, but not with later releases. Something changed, need to investigate.

**Comment by shvachko** [comment]
Here is the exception I saw while running tests:
```
org.apache.giraffa.TestBlockManagement > classMethod FAILED
    java.io.IOException: Shutting down
        at org.apache.hadoop.hbase.MiniHBaseCluster.init(MiniHBaseCluster.java:231)
        at org.apache.hadoop.hbase.MiniHBaseCluster.<init>(MiniHBaseCluster.java:93)
        at org.apache.hadoop.hbase.HBaseTestingUtility.startMiniHBaseCluster(HBaseTestingUtility.java:978)
        at org.apache.hadoop.hbase.HBaseTestingUtility.startMiniCluster(HBaseTestingUtility.java:938)
        at org.apache.hadoop.hbase.HBaseTestingUtility.startMiniCluster(HBaseTestingUtility.java:812)
        at org.apache.hadoop.hbase.HBaseTestingUtility.startMiniCluster(HBaseTestingUtility.java:794)
        at org.apache.hadoop.hbase.HBaseTestingUtility.startMiniCluster(HBaseTestingUtility.java:781)
        at org.apache.giraffa.TestBlockManagement.beforeClass(TestBlockManagement.java:50)

        Caused by:
        java.lang.RuntimeException: Failed construction of Master: class org.apache.hadoop.hbase.master.HMasterCan't assign requested address
            at org.apache.hadoop.hbase.util.JVMClusterUtil.createMasterThread(JVMClusterUtil.java:143)
            at org.apache.hadoop.hbase.LocalHBaseCluster.addMaster(LocalHBaseCluster.java:217)
            at org.apache.hadoop.hbase.LocalHBaseCluster.<init>(LocalHBaseCluster.java:153)
            at org.apache.hadoop.hbase.MiniHBaseCluster.init(MiniHBaseCluster.java:213)
            ... 7 more

            Caused by:
            java.net.BindException: Problem binding to /198.105.254.130:0 : Can't assign requested address
                at org.apache.hadoop.hbase.ipc.RpcServer.bind(RpcServer.java:2371)
                at org.apache.hadoop.hbase.ipc.RpcServer$Listener.<init>(RpcServer.java:524)
                at org.apache.hadoop.hbase.ipc.RpcServer.<init>(RpcServer.java:1899)
                at org.apache.hadoop.hbase.regionserver.RSRpcServices.<init>(RSRpcServices.java:792)
                at org.apache.hadoop.hbase.master.MasterRpcServices.<init>(MasterRpcServices.java:195)
                at org.apache.hadoop.hbase.master.HMaster.createRpcServices(HMaster.java:477)
                at org.apache.hadoop.hbase.regionserver.HRegionServer.<init>(HRegionServer.java:492)
                at org.apache.hadoop.hbase.master.HMaster.<init>(HMaster.java:333)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                at org.apache.hadoop.hbase.util.JVMClusterUtil.createMasterThread(JVMClusterUtil.java:139)
                ... 10 more

                Caused by:
                java.net.BindException: Can't assign requested address
                    at sun.nio.ch.Net.bind0(Native Method)
                    at sun.nio.ch.Net.bind(Net.java:433)
                    at sun.nio.ch.Net.bind(Net.java:425)
                    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
                    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
                    at org.apache.hadoop.hbase.ipc.RpcServer.bind(RpcServer.java:2369)
                    ... 22 more
```

**Comment by pjeli** [comment]
On my Macbook (OSX El Capitan 10.11), I am running with jdk1.8.0_91 with no issues.
