### ISSUE TITLE
Build #34 failed to pass TestRestartGiraffa

### ISSUE THREAD

**Issue by shvachko** [GiraffaFS/giraffa#38]
Original [issue 38](https://code.google.com/p/giraffa/issues/detail?id=38) created by shvachko on 2012-09-23T06:31:00.000Z:

Investigate what may have caused build #&nbsp;34 to fail on Jenkins and report if it can be fixed or if it was intermittent.

Here is a snap-shot of the issue:

java.io.IOException: Shutting down
    at org.apache.hadoop.hbase.MiniHBaseCluster.init(MiniHBaseCluster.java:203)
    at org.apache.hadoop.hbase.MiniHBaseCluster.&lt;init&gt;(MiniHBaseCluster.java:76)
    at org.apache.hadoop.hbase.HBaseTestingUtility.startMiniHBaseCluster(HBaseTestingUtility.java:632)
    at org.apache.hadoop.hbase.HBaseTestingUtility.startMiniCluster(HBaseTestingUtility.java:606)
    at org.apache.hadoop.hbase.HBaseTestingUtility.startMiniCluster(HBaseTestingUtility.java:554)
    at org.apache.hadoop.hbase.HBaseTestingUtility.startMiniCluster(HBaseTestingUtility.java:541)
    at org.apache.giraffa.TestRestartGiraffa.beforeClass(TestRestartGiraffa.java:39)
Caused by: java.lang.RuntimeException: Master not initialized after 200 seconds
    at org.apache.hadoop.hbase.util.JVMClusterUtil.startup(JVMClusterUtil.java:206)
    at org.apache.hadoop.hbase.LocalHBaseCluster.startup(LocalHBaseCluster.java:420)
    at org.apache.hadoop.hbase.MiniHBaseCluster.init(MiniHBaseCluster.java:196)

**Comment by shvachko** [comment]
Comment [#1](https://code.google.com/p/giraffa/issues/detail?id=38#c1) originally posted by shvachko on 2012-09-23T06:31:40.000Z:

The link: https://giraffa.ci.cloudbees.com/job/Giraffa/34/testReport/junit/junit.framework/TestSuite/org_apache_giraffa_TestRestartGiraffa/

**Comment by shvachko** [comment]
Comment [#2](https://code.google.com/p/giraffa/issues/detail?id=38#c2) originally posted by shvachko on 2012-09-24T17:42:48.000Z:

Looks like somehow the port was already in use. I think someone else was building / testing at the same time as us on the same machine somehow. It appears to have just been a one time thing. Closing.
