### ISSUE TITLE
INode and RowKey Path variables do not include URI

### ISSUE THREAD

**Issue by shvachko** [GiraffaFS/giraffa#39]
Original [issue 39](https://code.google.com/p/giraffa/issues/detail?id=39) created by shvachko on 2012-09-24T01:08:49.000Z:

Commands like ls, lsr, du, dus, stat, and others fail when they expect the output to include the URI in them because we never store the URI in either the RowKeys or the INodes.

Main causes are because we strip away the URI inside of GiraffaFileSystem using getPathName(), we never pass the URI down to the NamespaceProcessor. I propose we change this method to include the URI; refer to the first patch attached.

Once the URI is passed down, all RowKeys and INodes created use the full URI instead of just the Path. This will increase the overall size of the RowKey / INode, but it allows us to retain the URI information and complete du/dus commands.

I am attaching the changes I had to do from Issue #&nbsp;15 in order to get it work. Better implementation suggestions will be taken.

This issue is block Issue #&nbsp;15 from completion.

**Comment by shvachko** [comment]
Comment [#1](https://code.google.com/p/giraffa/issues/detail?id=39#c1) originally posted by shvachko on 2012-09-24T01:09:14.000Z:

&lt;empty&gt;

**Comment by shvachko** [comment]
Comment [#2](https://code.google.com/p/giraffa/issues/detail?id=39#c2) originally posted by shvachko on 2012-09-25T09:16:04.000Z:
1. Let's get rid of the parts belonging to issue 40 and issue 41 by committing them and regenerating the patch.
2. Looking at FullPathRowKey we need either of path or key member. It is a clear duplication. I tried removing key it worked well. That is  getKey() returns path.getBytes()
3. No need to add new column PATH. This is duplication of information because the path is already in the row key.
4. URI issue should be handled by call FS.makeQualified() in appropriate places. I'll take a closer look when 40-41 are committed and 39 is updated.

**Comment by shvachko** [comment]
Comment [#3](https://code.google.com/p/giraffa/issues/detail?id=39#c3) originally posted by shvachko on 2012-09-25T15:28:06.000Z:

Issue 40 and issue 41 are now committed. Here is the regenerated patch -- I will upload a NEW patch later today with your changes.

**Comment by shvachko** [comment]
Comment [#4](https://code.google.com/p/giraffa/issues/detail?id=39#c4) originally posted by shvachko on 2012-09-25T16:01:48.000Z:

Here is the patch with your changes in place. I ran the test -- back to 66% passing. With this patch it means FullPathRowKeys now use the full URI as their RowKey. We are failing the "cat" tests however, something I've gotten to pass before, but after the URI change, cannot seem to pass again.

Here is a sample output:
12/09/25 08:58:44 INFO cli.CLITestHelper: -------------------------------------------
12/09/25 08:58:44 INFO cli.CLITestHelper:                     Test ID: [219]
12/09/25 08:58:44 INFO cli.CLITestHelper:            Test Description: [cat: contents of file(absolute path) that does not exist]
12/09/25 08:58:44 INFO cli.CLITestHelper: 
12/09/25 08:58:44 INFO cli.CLITestHelper:               Test Commands: [-fs grfa://localhost:9000 -cat /file]
12/09/25 08:58:44 INFO cli.CLITestHelper: 
12/09/25 08:58:44 INFO cli.CLITestHelper: 
12/09/25 08:58:44 INFO cli.CLITestHelper:                  Comparator: [RegexpComparator]
12/09/25 08:58:44 INFO cli.CLITestHelper:          Comparision result:   [fail]
12/09/25 08:58:44 INFO cli.CLITestHelper:             Expected output:   [^cat: File does not exist: /file]
12/09/25 08:58:44 INFO cli.CLITestHelper:               Actual output:   [cat: File does not exist: grfa://localhost:9000/file
]

All of them fail due to the same issue. So it appears now that it is NOT expecting the URI. This may need some debugging to see where the discontinuity is coming from.

**Comment by shvachko** [comment]
Comment [#5](https://code.google.com/p/giraffa/issues/detail?id=39#c5) originally posted by shvachko on 2012-09-26T07:19:43.000Z:

I was thinking. We should not use full uri as a row key. The URI part, that is the address and the port can change in time if the service moves to another node or starts on a different port. And the row keys should still be valid.

We should really use only the path component as a key when we store it or look it up in the table. It is another thing how we return it back to applications. The client always knows the URI it is talking to. So the right way will be to construct URI part of the path on the client, when it receives the key from the NamespaceProcessor.

So the rule is simple: no URIs in NamespaceProcessor.

**Comment by shvachko** [comment]
Comment [#6](https://code.google.com/p/giraffa/issues/detail?id=39#c6) originally posted by shvachko on 2012-09-26T09:02:37.000Z:

Ok. I changed you patch just a bit to make FullPathRowKey work with path only, no URI. It passes our tests. CLI test fails expectedly, but I don't know how to count the percentage of passed tests vs failed. Let me know.

**Comment by shvachko** [comment]
Comment [#7](https://code.google.com/p/giraffa/issues/detail?id=39#c7) originally posted by shvachko on 2012-09-26T15:26:01.000Z:

Konstantin, while your patch does make it so the FPRK only works with the path; it causes us to fail tests that we should be passing:

You can just have to run TestGiraffaCLI.java as a JUnit test and read up a little bit from the very bottom of the console output (or just backwards search for 'pass' from the bottom).

12/09/26 08:16:06 INFO cli.CLITestHelper: ----------------------------------

12/09/26 08:16:06 INFO cli.CLITestHelper:                Testing mode: test
12/09/26 08:16:06 INFO cli.CLITestHelper: 
12/09/26 08:16:06 INFO cli.CLITestHelper:              Overall result: --- FAIL ---
12/09/26 08:16:06 INFO cli.CLITestHelper:                # Tests pass: 286 (45%)
12/09/26 08:16:06 INFO cli.CLITestHelper:                # Tests fail: 343 (54%)
12/09/26 08:16:06 INFO cli.CLITestHelper:          # Validations done: 1832 (each test may do multiple validations)
12/09/26 08:16:06 INFO cli.CLITestHelper: 
12/09/26 08:16:06 INFO cli.CLITestHelper: Failing tests:
12/09/26 08:16:06 INFO cli.CLITestHelper: --------------
12/09/26 08:16:06 INFO cli.CLITestHelper: 31: du: file using absolute path
12/09/26 08:16:06 INFO cli.CLITestHelper: 32: du: file using relative path
12/09/26 08:16:06 INFO cli.CLITestHelper: 33: du: files using globbing

I think the thing is in your patch you made it so INode path is key.getBytes(), which is non-URI. INode path needs to be URI so FsShell commands have the right output. I will re-work your patch and keep the RowKey URI-stripped.

**Comment by shvachko** [comment]
Comment [#8](https://code.google.com/p/giraffa/issues/detail?id=39#c8) originally posted by shvachko on 2012-09-26T15:41:32.000Z:

With the following patch we are back to 66%, and we still create RowKeys with the URI-stripped. If you look, the only change I made was that we need to introduce "path" into the FileFields because we should not rely on the RowKey to get the path.

This is actually the main issue: In NamespaceProcessor, we rely on the RowKey to contain the INode path information for us by using getPath() from it, which returns only the URI-stripped path. In order to get the full URI it needs to be given to INode by the create() and mkdirs() functions and held by ONLY the INode.

So here is the patch; review please. It bumps us back to 66% passing, 417 tests.

**Comment by shvachko** [comment]
Comment [#9](https://code.google.com/p/giraffa/issues/detail?id=39#c9) originally posted by shvachko on 2012-09-27T07:49:29.000Z:

Don't think storing URI in the table is the right solution.
The argument is the same. Suppose I start Giraffa on grfa://localhost:9000 and create /file1. Then stop it and restart on grfa://real.address.com:9999. The file status will return grfa://localhost:9000/file1. Which is not right.

We need to look into the client methods and transform URI-less paths returned by NamespaceProcessor by adding current grfa:// using makeQualified().

**Comment by shvachko** [comment]
Comment [#10](https://code.google.com/p/giraffa/issues/detail?id=39#c10) originally posted by shvachko on 2012-09-27T08:12:42.000Z:

Okay so storing the URI in the INode path is also invalid. In HDFS, the URI is okay because there is only 1 NameNode, is that correct? Or does HDFS not store the URI in the metadata either?

Okay so then I should look into overriding / changing the GiraffaClient methods? Is that correct?

**Comment by shvachko** [comment]
Comment [#11](https://code.google.com/p/giraffa/issues/detail?id=39#c11) originally posted by shvachko on 2012-09-27T08:20:01.000Z:

HDFS does not store the URI in the metadata.
You can check how it transforms path returned by NN to a URI.

**Comment by shvachko** [comment]
Comment [#12](https://code.google.com/p/giraffa/issues/detail?id=39#c12) originally posted by shvachko on 2012-09-27T08:25:23.000Z:

Do you know where the logs go, when I run test?

**Comment by shvachko** [comment]
Comment [#13](https://code.google.com/p/giraffa/issues/detail?id=39#c13) originally posted by shvachko on 2012-09-27T08:31:29.000Z:

Right now it should be under /build/test_reports. But I don't think those are "logs" of  output when the test ran... I know you can see output in Eclipse but maybe we need to setup a config in ant junit task to record logs?

**Comment by shvachko** [comment]
Comment [#14](https://code.google.com/p/giraffa/issues/detail?id=39#c14) originally posted by shvachko on 2012-09-27T08:34:00.000Z:

Nevermind, the .xml files contain the stderr output.

**Comment by shvachko** [comment]
Comment [#15](https://code.google.com/p/giraffa/issues/detail?id=39#c15) originally posted by shvachko on 2012-09-27T08:34:40.000Z:

Something is messed up with makeQualified(). It adds localhost:9000, when it should not. Also 3 slashes reduced to one. Example

12/09/27 01:10:29 INFO cli.CLITestHelper: -------------------------------------------
12/09/27 01:10:29 INFO cli.CLITestHelper:                     Test ID: [419]
12/09/27 01:10:29 INFO cli.CLITestHelper:            Test Description: [chmod: change permission(octal mode) of non existent file in grfa:// path]
12/09/27 01:10:29 INFO cli.CLITestHelper: 
12/09/27 01:10:29 INFO cli.CLITestHelper:               Test Commands: [-fs grfa://localhost:9000 -chmod 777 grfa:///file1]
12/09/27 01:10:29 INFO cli.CLITestHelper: 
12/09/27 01:10:29 INFO cli.CLITestHelper:            Cleanup Commands: [-fs grfa://localhost:9000 -rm grfa:///file1]
12/09/27 01:10:29 INFO cli.CLITestHelper: 
12/09/27 01:10:29 INFO cli.CLITestHelper:                  Comparator: [RegexpComparator]
12/09/27 01:10:29 INFO cli.CLITestHelper:          Comparision result:   [fail]
12/09/27 01:10:29 INFO cli.CLITestHelper:             Expected output:   [^chmod: could not get status for 'grfa:/file1': File does not exist: grfa:/file1]
12/09/27 01:10:29 INFO cli.CLITestHelper:               Actual output:   [chmod: could not get status for 'grfa:/file1': File does not exist: grfa://localhost:9000/file1

**Comment by shvachko** [comment]
Comment [#16](https://code.google.com/p/giraffa/issues/detail?id=39#c16) originally posted by shvachko on 2012-09-27T08:38:26.000Z:

Yeah if you look at the patch closely you will see that I had changed makeQualified() to add the URI. At the time it was the only solution I knew to get it working. I think I found something new / more correct to try. The following method is from DistributedFileSystem.

private FileStatus makeQualified(HdfsFileStatus f, Path parent) {
    return new FileStatus(f.getLen(), f.isDir(), f.getReplication(),
        f.getBlockSize(), f.getModificationTime(),
        f.getAccessTime(),
        f.getPermission(), f.getOwner(), f.getGroup(),
        (f.getFullPath(parent)).makeQualified(
            getUri(), getWorkingDirectory())); // fully-qualify path
  }

We need to add this and do the following conversion whenever we getListing() and getFileInfo(). I'll post up a patch that reverts our makeQualified() and adds this one.

**Comment by shvachko** [comment]
Comment [#17](https://code.google.com/p/giraffa/issues/detail?id=39#c17) originally posted by shvachko on 2012-09-27T08:56:39.000Z:

Another very common failure is that we return ls in wrong, well unexpected, order. Example

12/09/27 01:10:29 INFO cli.CLITestHelper:                  Comparator: [RegexpComparator]
12/09/27 01:10:29 INFO cli.CLITestHelper:          Comparision result:   [fail]
12/09/27 01:10:29 INFO cli.CLITestHelper:             Expected output:   [^-rw-rw-rw-( )_1( )_[a-z]_( )_supergroup( )_0( )_[0-9]{4,}-[0-9]{2,}-[0-9]{2,} [0-9]{2,}:[0-9]{2,}( )*/dir2/dir1/file1]
12/09/27 01:10:29 INFO cli.CLITestHelper:               Actual output:   [drwxrwxrwx   - shv supergroup          0 2012-09-27 01:09 /dir0/dir1
-rwxrwxrwx   1 shv supergroup          0 2012-09-27 01:09 /dir0/dir1/file2
-rwxrwxrwx   1 shv supergroup          0 2012-09-27 01:09 /dir0/dir1/file1
-rwxrwxrwx   1 shv supergroup          0 2012-09-27 01:09 /dir0/file0
drwxrwxrwx   - shv supergroup          0 2012-09-27 01:09 /dir2/dir1
-rwxrwxrwx   1 shv supergroup          0 2012-09-27 01:09 /dir2/dir1/file2
-rwxrwxrwx   1 shv supergroup          0 2012-09-27 01:09 /dir2/dir1/file1
-rwxrwxrwx   1 shv supergroup          0 2012-09-27 01:09 /dir2/file0
]

**Comment by shvachko** [comment]
Comment [#18](https://code.google.com/p/giraffa/issues/detail?id=39#c18) originally posted by shvachko on 2012-09-27T08:57:48.000Z:

Yeh, let's try that.

**Comment by shvachko** [comment]
Comment [#19](https://code.google.com/p/giraffa/issues/detail?id=39#c19) originally posted by shvachko on 2012-09-27T09:00:41.000Z:

I warned you that the HashMap implementation will not sort our directoryTables. I think this is a consequence if that because we grab files sequentially from directories by their childKeys.

Here is the patch -- I'm running it right now.

**Comment by shvachko** [comment]
Comment [#20](https://code.google.com/p/giraffa/issues/detail?id=39#c20) originally posted by shvachko on 2012-09-27T09:25:13.000Z:

My last patch is causing -moveFromLocal to hang on a complete() call.
I added debug print statements to testGiraffaCLI so I can see the commands:

cmd := -fs NAMENODE -moveFromLocal CLITEST_DATA/data15bytes /data15bytes
12/09/27 02:22:24 WARN conf.Configuration: mapred.used.genericoptionsparser is deprecated. Instead, use mapreduce.client.genericoptionsparser.used
12/09/27 02:22:24 INFO hbase.BlockManagementAgent: Altering put edits...
12/09/27 02:22:24 INFO hbase.BlockManagementAgent: al := [LocatedBlock{blk_6663403865954147761_1222; getBlockSize()=15; corrupt=false; offset=0; locs=[127.0.0.1:37559]}]
12/09/27 02:22:24 INFO namenode.FSEditLog: Number of transactions: 954 Total time for transactions(ms): 7Number of transactions batched in Syncs: 0 Number of syncs: 716 SyncTimes(ms): 1521 1192 
12/09/27 02:22:24 INFO ipc.Server: IPC Server handler 8 on 57774, call complete(/giraffa/finalized/gblk_6663403865954147761, DFSClient_hb_rs_localhost,46666,1348737685495, blk_6663403865954147761_1222) from 127.0.0.1:38069: error: org.apache.hadoop.hdfs.server.namenode.LeaseExpiredException: No lease on /giraffa/finalized/gblk_6663403865954147761 File is not open for writing. [Lease.  Holder: DFSClient_hb_rs_localhost,46666,1348737685495, pendingcreates: 2]
org.apache.hadoop.hdfs.server.namenode.LeaseExpiredException: No lease on /giraffa/finalized/gblk_6663403865954147761 File is not open for writing. [Lease.  Holder: DFSClient_hb_rs_localhost,46666,1348737685495, pendingcreates: 2]
    at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:1737)
    at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:1720)
    at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.completeFileInternal(FSNamesystem.java:1775)
    at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.completeFile(FSNamesystem.java:1758)
    at org.apache.hadoop.hdfs.server.namenode.NameNode.complete(NameNode.java:857)
    at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.hadoop.ipc.WritableRpcEngine$Server.call(WritableRpcEngine.java:349)
    at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:1482)
    at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:1478)
    at java.security.AccessController.doPrivileged(Native Method)

This was not failing before. It failing might not be a bad thing though. I will look into this issue later. I think we are on the right track for fixing this issue though.

**Comment by shvachko** [comment]
Comment [#21](https://code.google.com/p/giraffa/issues/detail?id=39#c21) originally posted by shvachko on 2012-09-27T09:59:21.000Z:

I looked into it and found it was a mistake with my previous patch. I fixed the issue -- this new patch was tested using testGiraffaCLI -- it runs cleanly, and it passes 67% of the tests! Thats the highest I've seen yet, in fact I think it is the limit for the current state of Giraffa, and it does it all without adding the URI to the meta-data!

Konstantin, I think we can safely say that this issue is closed. Please review my patch and let me know if its ready for commitment!

**Comment by shvachko** [comment]
Comment [#22](https://code.google.com/p/giraffa/issues/detail?id=39#c22) originally posted by shvachko on 2012-09-27T10:02:37.000Z:

And I have just confirmed that along with this patch all the previous tests also work. This looks stable! Get back to me about it whenever you can and I'll commit it ASAP. Then we can finally figure out how to close out issue 15!

**Comment by shvachko** [comment]
Comment [#23](https://code.google.com/p/giraffa/issues/detail?id=39#c23) originally posted by shvachko on 2012-09-27T17:40:17.000Z:

A quick question while this topic is still open -- why can't we "extends DistributedFileSystem" instead of "extends FileSystem"? That would have caught this issue. What are the main concerns for why we can't? Should I try to do it?

**Comment by shvachko** [comment]
Comment [#24](https://code.google.com/p/giraffa/issues/detail?id=39#c24) originally posted by shvachko on 2012-09-28T09:50:07.000Z:

> createFileStatus(HdfsFileStatus hdfsFile, Path parent)

Why parent? Just call it src. Also would be good to rename hdfsFile to hdfsStatus.

We should still have the change below in NapmespaceProcessor.newINode()
-        key.getPath().toString().getBytes(),
-        key.getKey(),

Nit. generateKey() should return getKey(), which is equivalent to your's, but reuses code.

Don't try "extends DistributedFileSystem". There will lot's of things HDFS related. But most importantly we will there will be DFSClient there, and what it to be GiraffaClient.

I see a bunch of outputs, like
12/09/28 02:38:50 INFO cli.CLITestHelper:               Actual output:   [ersion: Unknown command

Some of them are unavoidable, since we do not support all commands, but things like Quota commands should work in Giraffa already I think.
67% is great. How about we raise target to 75%? Quotas might just do it.

**Comment by shvachko** [comment]
Comment [#25](https://code.google.com/p/giraffa/issues/detail?id=39#c25) originally posted by shvachko on 2012-09-28T15:31:31.000Z:

I had copied the method out of DFS so that's why the naming was like that. I will make your changes and generate another patch.

Yeah I had tried to "extends DFS" last night and I saw it would require changing packages and a lot of funky stuff with DFSClient.

Those outputs that are [ersion...etc] are the DFSADMIN tests. They are part of testHDFSCLI but they cause testGRFACLI to fail if they execute so if you look at testGRFACLI.execute() I actually change DFSADMIN commands to FS commands (just asking for version). This is temporary.

I agree on getting the quotas to work. I'll look into it.

**Comment by shvachko** [comment]
Comment [#26](https://code.google.com/p/giraffa/issues/detail?id=39#c26) originally posted by shvachko on 2012-09-28T15:44:40.000Z:

> We should still have the change below in NapmespaceProcessor.newINode()
> -        key.getPath().toString().getBytes(),
> -        key.getKey(),

I disagree, that causes us to rely on key being equal to the path. That is only true for FullPathRowKey, if we changed to INodeRowKey or RandomNumberRowKey INodes will no longer work. I will not include this change in my new patch unless you can justify why it should be key.getKey().

**Comment by shvachko** [comment]
Comment [#27](https://code.google.com/p/giraffa/issues/detail?id=39#c27) originally posted by shvachko on 2012-09-28T23:38:31.000Z:

Yes you are right this is the path parameter. My bad.

**Comment by shvachko** [comment]
Comment [#28](https://code.google.com/p/giraffa/issues/detail?id=39#c28) originally posted by shvachko on 2012-09-29T00:58:35.000Z:

Here is the patch. Awaiting your review.

**Comment by shvachko** [comment]
Comment [#29](https://code.google.com/p/giraffa/issues/detail?id=39#c29) originally posted by shvachko on 2012-09-29T19:02:24.000Z:

&lt;empty&gt;

**Comment by shvachko** [comment]
Comment [#30](https://code.google.com/p/giraffa/issues/detail?id=39#c30) originally posted by shvachko on 2012-09-30T20:46:31.000Z:

Looks good. +1
There are several failures related to "File does not exist: " + src with fle name src not matching the expected. We should fix it in the next issue.

**Comment by shvachko** [comment]
Comment [#31](https://code.google.com/p/giraffa/issues/detail?id=39#c31) originally posted by shvachko on 2012-09-30T21:20:18.000Z:

Committed and closed.
