### ISSUE TITLE
Jenkins running into OutOfMemory errors post test

### ISSUE THREAD

**Issue by shvachko** [GiraffaFS/giraffa#60]
Original [issue 60](https://code.google.com/p/giraffa/issues/detail?id=60) created by shvachko on 2013-01-13T01:30:22.000Z:

It seems Jenkins is running into memory issues now:
https://giraffa.ci.cloudbees.com/job/Giraffa-TRUNK/

Builds 248, 249, and 250 failed with the same OoM errors.

I believe the tests are somehow consuming too much memory. One specific example I can point at is the TestGiraffaUpgrade test which creates a large FsImage and loads it into memory.

The garbage collector should clear this up, but we can also get away with creating a smaller FsImage.

**Comment by shvachko** [comment]
Comment [#1](https://code.google.com/p/giraffa/issues/detail?id=60#c1) originally posted by shvachko on 2013-01-13T19:22:46.000Z:

The tests seem to be finishing fine. Sounds like publishing JUnit test results fails. See below. Is it about disk resources?

[FINDBUGS] Collecting findbugs analysis files...
[FINDBUGS] Finding all files that match the pattern build/findbugs_reports/*.xml
[FINDBUGS] Parsing 1 files in /scratch/jenkins/workspace/Giraffa-TRUNK
[FINDBUGS] Successfully parsed file /scratch/jenkins/workspace/Giraffa-TRUNK/build/findbugs_reports/findbugs.xml of module  with 31 warnings.
[FINDBUGS] Computing warning deltas based on reference build #&nbsp;247
Recording test results
ERROR: Failed to archive test reports
hudson.util.IOException2: remote file operation failed: /scratch/jenkins/workspace/Giraffa-TRUNK at hudson.remoting.Channel@17e36248:s-3d5216d3
    at hudson.FilePath.act(FilePath.java:835)
    at hudson.FilePath.act(FilePath.java:821)
    at hudson.tasks.junit.JUnitParser.parse(JUnitParser.java:83)
    at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:122)
    at hudson.tasks.junit.JUnitResultArchiver.perform(JUnitResultArchiver.java:134)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
    at hudson.model.AbstractBuild$AbstractRunner.perform(AbstractBuild.java:720)
    at hudson.model.AbstractBuild$AbstractRunner.performAllBuildSteps(AbstractBuild.java:695)
    at hudson.model.Build$RunnerImpl.post2(Build.java:162)
    at hudson.model.AbstractBuild$AbstractRunner.post(AbstractBuild.java:642)
    at hudson.model.Run.run(Run.java:1467)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:239)
Caused by: java.io.IOException: Remote call on s-3d5216d3 failed
    at hudson.remoting.Channel.call(Channel.java:673)
    at hudson.FilePath.act(FilePath.java:828)
    ... 13 more
Caused by: java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:2882)
    at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:100)
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:515)
    at java.lang.StringBuilder.append(StringBuilder.java:189)
    at java.io.ObjectInputStream$BlockDataInputStream.readUTFSpan(ObjectInputStream.java:3098)
    at java.io.ObjectInputStream$BlockDataInputStream.readUTFBody(ObjectInputStream.java:3006)
    at java.io.ObjectInputStream$BlockDataInputStream.readLongUTF(ObjectInputStream.java:2989)
    at java.io.ObjectInputStream.readString(ObjectInputStream.java:1602)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1319)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1946)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1870)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1752)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:350)
    at java.util.ArrayList.readObject(ArrayList.java:593)
    at sun.reflect.GeneratedMethodAccessor1546.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:969)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1848)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1752)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1946)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1870)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1752)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:350)
    at hudson.remoting.UserRequest.deserialize(UserRequest.java:182)
    at hudson.remoting.UserResponse.retrieve(UserRequest.java:211)
    at hudson.remoting.Channel.call(Channel.java:665)
    at hudson.FilePath.act(FilePath.java:828)
    at hudson.FilePath.act(FilePath.java:821)
Build step 'Publish JUnit test result report' changed build result to FAILURE
Publishing Javadoc
Sending e-mails to: plamenj2003@yahoo.com shv.hadoop@gmail.com
Finished: FAILURE

**Comment by shvachko** [comment]
Comment [#2](https://code.google.com/p/giraffa/issues/detail?id=60#c2) originally posted by shvachko on 2013-01-13T21:41:47.000Z:

If you look, there is an OutOfMemory exception when the tests finish, during FindBugs. I am pretty sure somehow memory is not being freed post testing. I was also getting an OutOfMemory error on my Mac after tests suite finishes.

**Comment by shvachko** [comment]
Comment [#3](https://code.google.com/p/giraffa/issues/detail?id=60#c3) originally posted by shvachko on 2013-01-31T01:27:49.000Z:

So it appears there are some real issues at hand so far:

1) We create a new HBaseTestingUtil at every call of GiraffaTestingUtils.getHBaseTestUtil().
2) We use HBaseTestingUtil to create the MiniHBaseCluster, but we shut it down WITHOUT using the HBaseTestingUtil. We do this because using the TestingUtil to perform the shutdown causes a ZooKeeper session to fail to expire and then as we run all the tests our CPU becomes consumed with ZK threads trying to shutdown.
3) Therefore we leave it as it is right now and the ZK threads take over our memory as we continue.
4) Updating to HBase 0.94.3 does not resolve this issue and 0.94.4 is not available yet.

I have instead attached a patch to try to save memory where we can -- namely, in the GiraffaUpgrade test.
This should get us back to passing unit tests again.

**Comment by shvachko** [comment]
Comment [#4](https://code.google.com/p/giraffa/issues/detail?id=60#c4) originally posted by shvachko on 2013-01-31T03:03:54.000Z:

I am bumping up the priority on this as without it we cannot see any of the new changes we would like to add.

**Comment by shvachko** [comment]
Comment [#5](https://code.google.com/p/giraffa/issues/detail?id=60#c5) originally posted by shvachko on 2013-02-01T04:17:49.000Z:

How can I reproduce this on maven build? I'd like to pin down cause of this memory leak. Or maybe you have test server where this problem is reproducible? Stacktrace or logs would help in this case.

**Comment by shvachko** [comment]
Comment [#6](https://code.google.com/p/giraffa/issues/detail?id=60#c6) originally posted by shvachko on 2013-02-01T05:06:11.000Z:

I was getting it on the maven build as well. Not sure why it's not showing up for you. Perhaps it is environment sensitive?

You should be able to browse the Jenkins builds and look at the console reports from there: https://giraffa.ci.cloudbees.com/job/Giraffa-TRUNK/

**Comment by shvachko** [comment]
Comment [#7](https://code.google.com/p/giraffa/issues/detail?id=60#c7) originally posted by shvachko on 2013-02-07T03:31:26.000Z:

Apparently the real issue appears to be that I had "Retain long standard output/error" checked. There is a stern warning that using this option increases Jenkins memory usage. Our poor free server can't handle the load so I have disabled it and now the build appears to be passing again.

Running a second build to confirm and then I will close this issue out.

**Comment by shvachko** [comment]
Comment [#8](https://code.google.com/p/giraffa/issues/detail?id=60#c8) originally posted by shvachko on 2013-02-07T03:46:55.000Z:

This appears to be resolved now. Closing.

**Comment by shvachko** [comment]
Comment [#9](https://code.google.com/p/giraffa/issues/detail?id=60#c9) originally posted by shvachko on 2013-02-08T19:49:50.000Z:

Good catch, Plamen.

**Comment by shvachko** [comment]
Comment [#10](https://code.google.com/p/giraffa/issues/detail?id=60#c10) originally posted by shvachko on 2013-02-08T20:04:34.000Z:

As a side note -- there is definitely a Mac OSX bug that causes memory leak / ZK threads to not close properly; but it is far trickier to find at the moment so I am ignoring it. I should really build Giraffa in a VM again...

**Comment by shvachko** [comment]
Comment [#11](https://code.google.com/p/giraffa/issues/detail?id=60#c11) originally posted by shvachko on 2013-02-08T20:15:18.000Z:

So what do I do to make tests pass on my local box?
The build fails with OOM.

**Comment by shvachko** [comment]
Comment [#12](https://code.google.com/p/giraffa/issues/detail?id=60#c12) originally posted by shvachko on 2013-02-08T20:16:23.000Z:

I am on CentOs

**Comment by shvachko** [comment]
Comment [#13](https://code.google.com/p/giraffa/issues/detail?id=60#c13) originally posted by shvachko on 2013-02-09T03:10:03.000Z:

Ok I think I know what the problem is. Creating new issue.
