### ISSUE TITLE
Maven build follow up

### ISSUE THREAD

**Issue by shvachko** [GiraffaFS/giraffa#66]
Original [issue 66](https://code.google.com/p/giraffa/issues/detail?id=66) created by shvachko on 2013-02-17T04:23:12.000Z:

Need to quickly follow up with the following issues after issue #&nbsp;59 commit.
1. Jenkins build is naturally broken now as there is now build.xml
https://giraffa.ci.cloudbees.com/job/Giraffa-TRUNK/
2. Logs from the tests should not go to stdout, but rather into a file under target/ directory
3. Several tests are failing on my box using mvn test. Not sure if this is because I miss anything. 
Kostya do I need to install anything extra?

**Comment by shvachko** [comment]
Comment [#1](https://code.google.com/p/giraffa/issues/detail?id=66#c1) originally posted by shvachko on 2013-02-17T05:20:21.000Z:

Konstantin, 
1) I can setup Jenkins to build maven project -- I'll need temporary access to Jenkins configuration or I can help with instructions on how to do it. 
2) I'll do corresponding changes in pom.xml to redirect test output to target/std.log. 
Here are possible ways: 
   2.a) Totally redirect test output to target/std.log 
   2.b) Keep console std output + copy output to target/std.log
   2.c) Add maven profile which will activate file output. e.g. "mvn -Pfilelog clean install" will redirect all the output to target/std.log, whereas default configuration "mvn clean install" will use default behaviour of outputting to console. 

3) No, you don't need to install any extras. Please attach your console output and I'll try to pin down the problem. Before submitting patch I made sure that all the tests pass, so this might be specific to your OS/local env/etc.

---

in addition to above mentioned issues, we need to:
1) update clove.license file in src/test/clover/clover.license 
2) open Giraffa account on github or any other hosting where we can push site generated by maven build. e.g. just for demo purposes: http://kpelykh.github.com/giraffa/

**Comment by shvachko** [comment]
Comment [#2](https://code.google.com/p/giraffa/issues/detail?id=66#c2) originally posted by shvachko on 2013-02-17T07:18:37.000Z:

Plamen knows how to get Jenkins access. I just login via my gmail account.
Redirecting output should be a matter of configuring log4j. I think it prints to the screen if you don't configure it. No?
Plamen, do you have clover license. I thought you got it.
Let's hold on to publishing artifacts until we have a release.

I've been looking at the changes:
1. TestBlockManager is failing because it cannot find grfa.jar
   The jar file should be specified as a URI both in giraffa-default.xml and via grfa.test.jar.file. Like
   file://target/giraffa-0.0.1-SNAPSHOT.jar
2. The artifact should be named giraffa, not hadoop-hdfs-giraffa

**Comment by shvachko** [comment]
Comment [#3](https://code.google.com/p/giraffa/issues/detail?id=66#c3) originally posted by shvachko on 2013-02-17T07:32:10.000Z:
1. There should be no giraffa-site.xml in test resources.

**Comment by shvachko** [comment]
Comment [#4](https://code.google.com/p/giraffa/issues/detail?id=66#c4) originally posted by shvachko on 2013-02-17T08:58:29.000Z:

2) There's an existing option in maven test pluging to redirect all the output to files:

"mvn clean install -DredirectTestOutputToFile=true"

This will create a set of files, which will include all the test output, eg: 

target/surefire-reports/org.apache.giraffa.TestBlockManagement-output.txt
target/surefire-reports/org.apache.giraffa.TestBlockManagement.txt
target/surefire-reports/org.apache.giraffa.TestDirectoryTable-output.txt
target/surefire-reports/org.apache.giraffa.TestDirectoryTable.txt
....

By using this option, which is already build into maven we can avoid direct modification of log4j.properties and hard-coding output paths specific to a build process. 

redirectTestOutputToFile option can be enabled from command line as -DredirectTestOutputToFile=true, or can be defaulted to either true or false in  <configuration> section of maven-surefire-plugin in pom.xml.

# 
1. The reason why I had to put giraffa-site.xml into test/resources is because during tests, grfa.jar.file needs to point to a jar file. The path is dynamically calculated from the following expression, defended in pom.xml:

<grfa.test.jar.filename>${basedir}/target/${project.build.finalName}.${project.packaging}</grfa.test.jar.filename>

Jar filename can change from build to build therefore maven test plugin passes -Dgrfa.test.jar.file=.... and uses variable substitution in giraffa-site.xml to set correct value of 'grfa.jar.file' for tests to run. 

'src/test/resources/giraffa-site.xml' defines only test specific properties required to run the tests and none of those files will ever get into production package, as opposed to giraffa-default.xml which in located in src/main/resources/giraffa-default.xml.

If there's any better way to pass correct path to jar file through 'grfa.jar.file' property during tests run, I'm probably missing it. Please let me know and I will change how path to the jar file is passed.

Usually I try to keep test/build properties separate from production. And it might be a good idea not to introduce test-specific variable into giraffa-default.xml or log4j.properties as it will keep config files clean from build/test artifacts.

**Comment by shvachko** [comment]
Comment [#5](https://code.google.com/p/giraffa/issues/detail?id=66#c5) originally posted by shvachko on 2013-02-17T20:24:42.000Z:

I will take a look at Jenkins and make it a maven build now -> "mvn clean install -DredirectTestOutputToFile=true".

**Comment by shvachko** [comment]
Comment [#6](https://code.google.com/p/giraffa/issues/detail?id=66#c6) originally posted by shvachko on 2013-02-17T20:26:39.000Z:

I also have the Clover license. I will email it privately to both of you.

**Comment by shvachko** [comment]
Comment [#7](https://code.google.com/p/giraffa/issues/detail?id=66#c7) originally posted by shvachko on 2013-02-17T20:46:57.000Z:

It seems we are hitting connection refused and null pointer exceptions.
You can view the latest console here: https://giraffa.ci.cloudbees.com/job/Giraffa-TRUNK/327/consoleFull

The most common exception appears to be:
13/02/17 12:44:11 FATAL master.HMaster: Unhandled exception. Starting shutdown.
java.net.BindException: Port in use: 0.0.0.0:60010
    at org.apache.hadoop.http.HttpServer.start(HttpServer.java:628)
    at org.apache.hadoop.hbase.master.HMaster.startServiceThreads(HMaster.java:851)
    at org.apache.hadoop.hbase.master.HMaster.finishInitialization(HMaster.java:507)
    at org.apache.hadoop.hbase.master.HMaster.run(HMaster.java:344)
    at java.lang.Thread.run(Thread.java:722)
Caused by: java.net.BindException: Address already in use
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Net.java:344)
    at sun.nio.ch.Net.bind(Net.java:336)
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:199)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)...

Are we forking tests? We should not be I think. Not sure what else could be causing this apart from someone else ALSO using HBase ports.

**Comment by shvachko** [comment]
Comment [#8](https://code.google.com/p/giraffa/issues/detail?id=66#c8) originally posted by shvachko on 2013-02-18T02:56:32.000Z:

1) In order not to expose clover.license as a part of project sources we can put it under ~/.m2/clover.license on both jenkins and local machines and change pom.xml to point to ~/.m2/clover.license.

2) I made a mistake in command line "mvn clean install -DredirectTestOutputToFile=true" it should be 

mvn clean install -Dmaven.test.redirectTestOutputToFile=true

3) By default maven test plugin spawns only one process to run all tests in sequence (http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#forkMode).  The reason for "Port in use: 0.0.0.0:60010" exception is that maven spawns a java process (A) to run the tests and sometimes main maven process is cancelled by a user (Ctrl+C) or external command leaving test process (A) to run in background. The next time when the build is started another test process (B) is spawned and you see this exception, because the first process (A) is still running in background and keep ports open. Correct way to fix the problem would be to find out why tests are keeping at least one non-daemon thread running therefore not letting jvm to shutdown gracefully. I saw similar behaviour in Hadoop Minicluster so it might be related to MiniHBaseCluster not shutting down correctly. I'll be looking into this in more detail, but for now as a workaround we can use "forkedProcessTimeoutInSeconds" property of maven test plugin (http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#forkedProcessTimeoutInSeconds) which should forcefully shutdown test jvm after certain timeout (500 sec).

**Comment by shvachko** [comment]
Comment [#9](https://code.google.com/p/giraffa/issues/detail?id=66#c9) originally posted by shvachko on 2013-02-18T03:17:00.000Z:

Plamen, please check if ProcessTreeKiller is enabled in Jenkins. It should be watching all spawned processes and kill them whenever parent process is destroyed. 

https://wiki.jenkins-ci.org/display/JENKINS/ProcessTreeKiller

**Comment by shvachko** [comment]
Comment [#10](https://code.google.com/p/giraffa/issues/detail?id=66#c10) originally posted by shvachko on 2013-02-18T04:38:58.000Z:

Our Jenkins is hosted by CloudBees and therefore I don't think we can alter the Jenkins installation.

**Comment by shvachko** [comment]
Comment [#11](https://code.google.com/p/giraffa/issues/detail?id=66#c11) originally posted by shvachko on 2013-02-18T05:38:30.000Z:

Plamen, can you try to restart Jenkins instance using /restart url and rerun the build (ref. http://stackoverflow.com/questions/12355588/how-do-i-forcibly-kill-a-jenkins-build-in-cloudbees). I guess test process is stuck and it keeps ports open.

**Comment by shvachko** [comment]
Comment [#12](https://code.google.com/p/giraffa/issues/detail?id=66#c12) originally posted by shvachko on 2013-02-18T07:42:11.000Z:

By default Ant runs all the tests in the same process (as build) therefore if you shutdown build process, then you also stop test and free up all the associated resources (including ports). Maven by default runs tests in a spawned process, therefore sometimes you can run into "Port in use" when process didn't terminate. 

In attached patch:
1) I switched maven tests to use the same model as Ant (run tests in the same process as build), so no more "Port in use" errors, however it brings its own problems -- one of them is that output of maven build lifecycle is interleaved with tests output. Another problem is that no way to pass test-specific jvm arguments. 

This can be a good workaround for now to get build back to normal, but a long term solution would be to run tests in a separate process and verify that all resources are freed up when tests finish, so that tests process is gracefully shutdown and don't keep any resources from closing.

2) renamed artifact name from hadoop-hdfs-giraffa to giraffa

3) removed giraffa-site.xml from test resources. Now grfa.test.jar.file is passed as a system property and configured dynamically for every test in @Before method. 

# 

I didn't include new clover license, since this will expose it to the public. 
For local builds we can put it in ~/.m2 folder, but I doubt that we can do this for  Jenkins which runs in CloudBees. Plament, is there a private persistent file storage in CloudBees, that we can use to store clover.license and reference from pom.xml file? 

Also clover creates its own database. For now its path is set to ${project.basedir}/clover, but it would be better to move it to a persistent storage.

**Comment by shvachko** [comment]
Comment [#13](https://code.google.com/p/giraffa/issues/detail?id=66#c13) originally posted by shvachko on 2013-02-18T09:55:05.000Z:

Good call on the Jenkins reset. That appears to have fixed the unit tests. No need to revert back to Ant tests.

So I was able to add the Clover license key into Jenkins directly. It should be configured automatically to run now; I think I just need to add the clover:clover target, though I am not sure HOW Maven is going to grab the license key from Jenkins.

I was looking at this: https://wiki.jenkins-ci.org/display/JENKINS/Clover+Plugin.
Messing around with Jenkins right now.

2) and 3) are still needed however.

**Comment by shvachko** [comment]
Comment [#14](https://code.google.com/p/giraffa/issues/detail?id=66#c14) originally posted by shvachko on 2013-02-18T19:52:02.000Z:

Attached patch fixes 2) and 3). 
THe patch also changes path to find clover.license. Now it looks for the license under ~/.m2/clover.license. Everybody who wants to run "mvn clean site" to generate reports including clover will need to put clove.license under ~/.m2

**Comment by shvachko** [comment]
Comment [#15](https://code.google.com/p/giraffa/issues/detail?id=66#c15) originally posted by shvachko on 2013-02-18T22:32:32.000Z:

Committing now +1.

**Comment by shvachko** [comment]
Comment [#16](https://code.google.com/p/giraffa/issues/detail?id=66#c16) originally posted by shvachko on 2013-02-18T23:04:45.000Z:

I just committed this. Thank you Plamen.

**Comment by shvachko** [comment]
Comment [#17](https://code.google.com/p/giraffa/issues/detail?id=66#c17) originally posted by shvachko on 2013-02-19T04:01:53.000Z:

I think most of the credit here is Konst P. :)

**Comment by shvachko** [comment]
Comment [#18](https://code.google.com/p/giraffa/issues/detail?id=66#c18) originally posted by shvachko on 2013-02-19T07:34:36.000Z:

&lt;empty&gt;

**Comment by shvachko** [comment]
Comment [#19](https://code.google.com/p/giraffa/issues/detail?id=66#c19) originally posted by shvachko on 2013-02-20T07:35:01.000Z:

Of course thanks to Kostya. I'll correct CHANGES.txt
Sorry my mistake. Carried over from another issue.
