### ISSUE TITLE
Jenkins build is broken due to missing dependencies

### ISSUE THREAD

**Issue by shvachko** [GiraffaFS/giraffa#77]
Original [issue 77](https://code.google.com/p/giraffa/issues/detail?id=77) created by shvachko on 2013-08-12T05:52:58.000Z:

Jenkins is failing to build giraffa with the following error:

[ERROR] Failed to execute goal on project giraffa-core: Could not resolve dependencies for project org.apache.hadoop:giraffa-core:jar:0.0.2-SNAPSHOT: The following artifacts could not be resolved: org.apache.hbase:hbase-common:jar:0.95.1, org.apache.hbase:hbase-common:jar:tests:0.95.1, org.apache.hbase:hbase-client:jar:0.95.1, org.apache.hbase:hbase-client:jar:tests:0.95.1, org.apache.hbase:hbase-protocol:jar:0.95.1, org.apache.hbase:hbase-protocol:jar:tests:0.95.1, org.apache.hbase:hbase-server:jar:0.95.1, org.apache.hbase:hbase-server:jar:tests:0.95.1, org.apache.hbase:hbase-hadoop-compat:jar:tests:0.95.1, org.apache.hbase:hbase-hadoop-compat:jar:0.95.1, org.apache.hbase:hbase-hadoop2-compat:jar:0.95.1, org.apache.hbase:hbase-hadoop2-compat:jar:tests:0.95.1, org.apache.hbase:hbase-it:jar:0.95.1, org.apache.hbase:hbase-it:jar:tests:0.95.1: Failure to find org.apache.hbase:hbase-common:jar:0.95.1 in http://repo.cloudbees.com/content/repositories/central was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -&gt; [Help 1]

This error was introduced by changes related to issue #&nbsp;55 in pom.xml. Maven Central doesn't have hbase dependencies of version 0.95.1, but 0.95.1-hadoop1. If this is the same version of hbase, but just different naming convention, then fix should be trivial.

**Comment by shvachko** [comment]
Comment [#1](https://code.google.com/p/giraffa/issues/detail?id=77#c1) originally posted by shvachko on 2013-08-12T17:31:03.000Z:

Issue is known.

HBase split its versioning post-0.95.0 into 2 versions: 0.95.1-hadoop1 and 0.95.1-hadoop2.
They have published the Hadoop 1 compatible jars but not the Hadoop 2 compatible jars.

We cannot use 0.95.1-hadoop1 jars to compile Giraffa. Need to wait for a "-hadoop2" release / publish.

**Comment by shvachko** [comment]
Comment [#2](https://code.google.com/p/giraffa/issues/detail?id=77#c2) originally posted by shvachko on 2013-08-15T22:14:04.000Z:

I was thinking if we should stop jenkins builds for now.
I'll check with HBase guys where they stand on publishing artifacts for 0.95.1-hadoop2.

**Comment by shvachko** [comment]
Comment [#3](https://code.google.com/p/giraffa/issues/detail?id=77#c3) originally posted by shvachko on 2013-08-15T22:23:17.000Z:

Optionally we can install missing dependencies in hosted maven repo (e.g. on github) and use it till official artifacts appear in maven central

**Comment by shvachko** [comment]
Comment [#4](https://code.google.com/p/giraffa/issues/detail?id=77#c4) originally posted by shvachko on 2013-08-16T00:53:48.000Z:

Message from Stack:
 We just published 0.95.2 along with all artifacts to maven.   Try it?
Let's try it.

**Comment by shvachko** [comment]
Comment [#5](https://code.google.com/p/giraffa/issues/detail?id=77#c5) originally posted by shvachko on 2013-08-18T21:26:18.000Z:

HBase 0.95.2 doesn't seem to be published on maven yet: http://mvnrepository.com/artifact/org.apache.hbase/hbase. But judging by https://issues.apache.org/jira/browse/HBASE/fixforversion/12320040, it will be soon?

**Comment by shvachko** [comment]
Comment [#6](https://code.google.com/p/giraffa/issues/detail?id=77#c6) originally posted by shvachko on 2013-08-18T23:53:24.000Z:

It is published actually.

I am working on a patch.

**Comment by shvachko** [comment]
Comment [#7](https://code.google.com/p/giraffa/issues/detail?id=77#c7) originally posted by shvachko on 2013-08-19T04:30:51.000Z:

I keep hitting this error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (generate) on project giraffa-core: An Ant BuildException has occured: java.lang.NoSuchFieldError: JSP_VERSION_2_0
[ERROR] around Ant part ...<jspcompiler uriroot="${src.webapps}" package="org.apache.giraffa.web" webxml="${build.webapps}/WEB-INF/web.xml" outputdir="${generated.sources}/java"/>... @ 17:155 in /Users/plamenjeliazkov/giraffa/giraffa-core/target/antrun/build-main.xml

I can't seem to get a way around it. Milan, we encountered this before right? Do you remember what you did to fix it?

**Comment by shvachko** [comment]
Comment [#8](https://code.google.com/p/giraffa/issues/detail?id=77#c8) originally posted by shvachko on 2013-08-19T06:57:20.000Z:

Good news and bad news. Seems i've got the build working again -- need to exclude javax-servlet-api now? Not sure why.

However, API changes are getting us now. We have to switch over to using Cell API now. KeyValue will no longer be supported and in-fact, are broken now as of 0.95.2. I will take this over.

**Comment by shvachko** [comment]
Comment [#9](https://code.google.com/p/giraffa/issues/detail?id=77#c9) originally posted by shvachko on 2013-08-19T06:59:30.000Z:

Attaching incomplete patch. Its enough for you to get the build going and see the errors I am currently running into with regard to KeyValue vs Cell issues.

**Comment by shvachko** [comment]
Comment [#10](https://code.google.com/p/giraffa/issues/detail?id=77#c10) originally posted by shvachko on 2013-08-20T07:24:20.000Z:

Plamen, I'm still getting the JSP error after applying your patch. Is it possible that one of your changes didn't get put on to the patch? I don't see javax-servlet-api listed as a dependency either (perhaps because it's excluded).

We encountered this multiple times before, and each time we fixed using some bizarre combination of excluding some of the jsp jars and jasper jars. It was basically trial and error, and I still don't understand why that error would come up or why the exclusions fixed it. And somehow here I am getting the error while you aren't.

**Comment by shvachko** [comment]
Comment [#11](https://code.google.com/p/giraffa/issues/detail?id=77#c11) originally posted by shvachko on 2013-08-20T16:40:58.000Z:

Yeah actually it just changed on me. I swear it was working but now it no longer is. Maybe HBase was republished with new dependencies? I don't know...

Anyway, yeah I will try more bizarre combinations for now.

Kostya, this is related to the webUI JSP generation. Would you mind giving us a hand with this? I am unsure which dependencies are related to the JspC and causing this issue.

**Comment by shvachko** [comment]
Comment [#12](https://code.google.com/p/giraffa/issues/detail?id=77#c12) originally posted by shvachko on 2013-08-20T16:51:52.000Z:

Sorry for not participating in discussion, lately work has been super crazy for me. Let me debug though the code today and I'll try to find root cause of the problem. I saw similar problems before, so I think I know what to look for.

**Comment by shvachko** [comment]
Comment [#13](https://code.google.com/p/giraffa/issues/detail?id=77#c13) originally posted by shvachko on 2013-08-20T23:12:13.000Z:

No problem Kostya. Sorry for any inconviences.

Neither Milan nor I are quite sure what is causing this issue though.
Thanks for your help.

**Comment by shvachko** [comment]
Comment [#14](https://code.google.com/p/giraffa/issues/detail?id=77#c14) originally posted by shvachko on 2013-08-21T07:55:59.000Z:

I fixed problem with JSP. Web UI comes up, however link to Namenode page and Hbase are broken, also some placeholders are not getting substituted with a string. Good news is that HBase table and Giraffa Browser work fine. 

While testing I noticed a bug introduced by 6f927777fb27400377ec73841f7df1daff5f9d9f checkin, here's a stack trace: 

13/08/20 23:56:08 ERROR ipc.RpcServer: Unexpected throwable object 
java.lang.NullPointerException
    at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$AddBlockResponseProto$Builder.setBlock(ClientNamenodeProtocolProtos.java:9361)
    at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:299)
    at org.apache.giraffa.hbase.NamespaceProcessor.addBlock(NamespaceProcessor.java:243)
    at org.apache.giraffa.hbase.NamespaceProcessorProtos$NamespaceProcessor.callMethod(NamespaceProcessorProtos.java:2035)
    at org.apache.hadoop.hbase.regionserver.HRegion.execService(HRegion.java:5120)
    at org.apache.hadoop.hbase.regionserver.HRegionServer.execService(HRegionServer.java:3220)
    at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:20807)
    at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2156)
    at org.apache.hadoop.hbase.ipc.RpcServer$Handler.run(RpcServer.java:1861)
13/08/20 23:56:19 WARN client.RpcRetryingCaller: Call exception, tries=0, retries=31, retryTime=-24797ms
java.io.IOException: java.io.IOException
    at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2194)
    at org.apache.hadoop.hbase.ipc.RpcServer$Handler.run(RpcServer.java:1861)
Caused by: java.lang.NullPointerException
    at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$AddBlockResponseProto$Builder.setBlock(ClientNamenodeProtocolProtos.java:9361)
    at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:299)
    at org.apache.giraffa.hbase.NamespaceProcessor.addBlock(NamespaceProcessor.java:243)
    at org.apache.giraffa.hbase.NamespaceProcessorProtos$NamespaceProcessor.callMethod(NamespaceProcessorProtos.java:2035)
    at org.apache.hadoop.hbase.regionserver.HRegion.execService(HRegion.java:5120)
    at org.apache.hadoop.hbase.regionserver.HRegionServer.execService(HRegionServer.java:3220)
    at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:20807)
    at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2156)
    ... 1 more

This error can be reproduced by running "mvn -Pwebdemo" from giraffa-core

The same error shows up in tests.

**Comment by shvachko** [comment]
Comment [#15](https://code.google.com/p/giraffa/issues/detail?id=77#c15) originally posted by shvachko on 2013-08-21T18:34:22.000Z:

Thank you Kostya! This does indeed address the JspC issue. My other "exclusions" were un-necessary; I'll remove them in a follow-up patch.

The issue you brought up was actually introduced by the HBase change. For some reason when we call "addBlock" it is not storing the LocatedBlock returned from NameNode in our HBase row; we've encountered this issue before I recall, right Milan?

The setBlock call here at the top of the stacktrace is from setting the "previous" block; which is null in this case because it was not seen in the row when we do our Get following updateINode(node, BlockAction.ALLOCATE).

**Comment by shvachko** [comment]
Comment [#16](https://code.google.com/p/giraffa/issues/detail?id=77#c16) originally posted by shvachko on 2013-08-21T21:28:07.000Z:

Okay guys, I think this is the one. I see all unit tests passing with this. Please try and verify!

Will open another issue to fix up webUI.

**Comment by shvachko** [comment]
Comment [#17](https://code.google.com/p/giraffa/issues/detail?id=77#c17) originally posted by shvachko on 2013-08-21T22:01:07.000Z:

Great seeing team work, guys :-)
Kostya, welcome back.

**Comment by shvachko** [comment]
Comment [#18](https://code.google.com/p/giraffa/issues/detail?id=77#c18) originally posted by shvachko on 2013-08-21T22:26:32.000Z:

Hey Plamen, I am unable to run testGiraffaCLI: FileNotFoundException: giraffa-core/src/test/resources/testHDFSConf.xml. Weird because that file definitely does exist. I'll try running the tests from a new clone and see if that changes anything. The rest of them pass though.

Also, for some reason, the tests now take much longer to run on my computer because they are taking several minutes to get the minicluster running. The problem seems to be with the Zookeeper connection:

WARN zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=localhost:56917, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase

Eventually the minicluster is set up and the tests continue and pass. Are you also having this problem?

**Comment by shvachko** [comment]
Comment [#19](https://code.google.com/p/giraffa/issues/detail?id=77#c19) originally posted by shvachko on 2013-08-21T23:19:52.000Z:

I saw the FileNotFoundException originally when it was previously just src/test/resources/testHDFSConf.xml -- try reverting that one line back and see if that works; if it does then lets keep it working with maven.

I do not see the ZooKeeper issue though... not sure what that is.

**Comment by shvachko** [comment]
Comment [#20](https://code.google.com/p/giraffa/issues/detail?id=77#c20) originally posted by shvachko on 2013-08-22T02:26:35.000Z:

Yeah I changed it to src/ and it works now. The other way fails both in Eclipse and in maven. But the other way works for you?

**Comment by shvachko** [comment]
Comment [#21](https://code.google.com/p/giraffa/issues/detail?id=77#c21) originally posted by shvachko on 2013-08-22T17:24:47.000Z:

Konst, thanks! I was not too far away, just working really hard on a project which can turn into full-time thing, so it eats all of my time right now. :(

Alrighty guys, some more JSP black magic and we got fully working UI back again. 
All tests pass this time and I'm not seeing above-mentioned exceptions. 

By the way, UI can be tested by running "mvn -Pwebdemo" from giraffa-core. It will automatically bring up minicluster and populate it with some dummy data. When server is up, you should be able to see UI at "http://localhost:40010". To gracefully shutdown the server, just type "stop" in the console.

**Comment by shvachko** [comment]
Comment [#22](https://code.google.com/p/giraffa/issues/detail?id=77#c22) originally posted by shvachko on 2013-08-22T17:40:06.000Z:

Very nice. I'll try out this.

**Comment by shvachko** [comment]
Comment [#23](https://code.google.com/p/giraffa/issues/detail?id=77#c23) originally posted by shvachko on 2013-08-24T18:13:59.000Z:

This patch works for me. All tests passing, zero findbugs, and the web UI is working. I'm still getting the possibly transient zookeeper exceptions, but i think it's something ipv6 related on my end. One small thing: since we're modifying the pom, we should take this opportunity to move the hbase comment on giraffa-core's pom.xml line 155 to line 202 so that it is easier to navigate the pom.

**Comment by shvachko** [comment]
Comment [#24](https://code.google.com/p/giraffa/issues/detail?id=77#c24) originally posted by shvachko on 2013-08-24T18:37:38.000Z:

While testing the standalone, I noticed that HBase 0.95.2 is built using Hadoop 2.0.5 (0.95.1 was built with Hadoop 2.0.2). So we need to upgrade to 2.0.5, and there are some API changes. During the Hadoop 2 upgrade, I had initially upgraded to 2.0.5 so I remember what's needed, so I can take on this task. There are only a few minor changes if I recall. Strictly speaking, upgrading to Hadoop 2.0.5 does not affect the Jenkins build, so should this be a separate task?

**Comment by shvachko** [comment]
Comment [#25](https://code.google.com/p/giraffa/issues/detail?id=77#c25) originally posted by shvachko on 2013-08-24T19:05:38.000Z:

Milan, I think separate task makes sense, since this task was about maven build, but now it also includes fixes for UI. Just to keep things clear, I would suggest to create a separate issue.

**Comment by shvachko** [comment]
Comment [#26](https://code.google.com/p/giraffa/issues/detail?id=77#c26) originally posted by shvachko on 2013-08-25T16:47:28.000Z:

&lt;empty&gt;

**Comment by shvachko** [comment]
Comment [#27](https://code.google.com/p/giraffa/issues/detail?id=77#c27) originally posted by shvachko on 2013-08-26T02:05:30.000Z:

I just committed this. Thanks Plamen and Kostya.
It should fix the build. Please file follow up issues as needed.
